version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=promotion_app
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
# server:
#   build: 
#     context: .
#     dockerfile: Dockerfile
#   depends_on:
#     - db
#   volumes:
#     - type: bind
#       source: .
#       target: /app
#   ports: 
#     - "5000:5000"